<?php

namespace AppBundle\Entity;
use UserBundle\Entity\User;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser(User $user) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b, r FROM AppBundle:Booking b LEFT JOIN b.review r WHERE r.user = :authorId'
            )
            ->setParameters(['authorId' => $user->getId()])
            ->getResult();
    }
}
